function flattenMinecraftBlocks(input: unknown): Set<string> {
	const result = new Set<string>();

	function recurse(value: unknown): void {
		if (typeof value === "string") {
			result.add(value);
		} else if (Array.isArray(value)) {
			for (const item of value) {
				recurse(item);
			}
		} else if (typeof value === "object" && value !== null) {
			for (const key in value as Record<string, unknown>) {
				recurse((value as Record<string, unknown>)[key]);
			}
		}
	}

	recurse(input);
	return result;
}


export function flattenMinecraftBlocksArgs(...inputs: unknown[]): Set<string> {
	let result = new Set<string>();

	for (const input of inputs) {
		if (typeof input === "string") {
			result.add(input);
		} else if (Array.isArray(input)) {
			result = new Set([...result, ...flattenMinecraftBlocks(input)])
		} else if (typeof input === "object" && input !== null) {
			result = new Set([...result, ...flattenMinecraftBlocks(input)])
			//result.union(flattenMinecraftBlocks(input));
		}
	}

	return result;
}



export type MinecraftBlocks = keyof typeof minecraftBlocks;

export const minecraftBlocks = {
	woods: {
		log: [
			"acacia_log",
			"birch_log",
			"cherry_log",
			"dark_oak_log",
			"jungle_log",
			"mangrove_log",
			"oak_log",
			"pale_oak_log",
			"spruce_log",
		],
		planks: [
			"acacia_planks",
			"bamboo_planks",
			"birch_planks",
			"cherry_planks",
			"crimson_planks",
			"dark_oak_planks",
			"jungle_planks",
			"mangrove_planks",
			"oak_planks",
			"pale_oak_planks",
			"spruce_planks",
			"warped_planks",
			"bamboo_mosaic",
		],
		wood: [
			"acacia_wood",
			"birch_wood",
			"cherry_wood",
			"crimson_stem",
			"dark_oak_wood",
			"jungle_wood",
			"mangrove_wood",
			"oak_wood",
			"pale_oak_wood",
			"spruce_wood",
			"warped_stem",
			"bamboo_block",
			"crimson_hyphae",
			"warped_hyphae",
		],
		stripped: {
			log: [
				"acacia_stripped_log",
				"birch_stripped_log",
				"cherry_stripped_log",
				"dark_oak_stripped_log",
				"jungle_stripped_log",
				"mangrove_stripped_log",
				"oak_stripped_log",
				"pale_oak_stripped_log",
				"spruce_stripped_log",
			],
			wood: [
				"acacia_stripped_wood",
				"birch_stripped_wood",
				"cherry_stripped_wood",
				"dark_oak_stripped_wood",
				"jungle_stripped_wood",
				"mangrove_stripped_wood",
				"oak_stripped_wood",
				"pale_oak_stripped_wood",
				"spruce_stripped_wood",
				"stripped_bamboo_block",
				"stripped_crimson_stem",
				"stripped_warped_stem",
				"stripped_crimson_hyphae",
				"stripped_warped_hyphae",
			],
		},
	},
	leaves: [
		"acacia_leaves",
		"azalea_leaves",
		"flowering_azalea_leaves",
		"birch_leaves",
		"cherry_leaves",
		"dark_oak_leaves",
		"jungle_leaves",
		"mangrove_leaves",
		"oak_leaves",
		"pale_oak_leaves",
		"spruce_leaves",
	],
	stones: {
		natural: [
			"stone",
			"tuff",
			"andesite",
			"blackstone",
			"sandstone",
			"red_sandstone",
			"cobbled_deepslate",
			"basalt",
			"calcite",
			"cobblestone",
			"mossy_cobblestone",
			"dripstone_block",
			"deepslate",
			"diorite",
			"granite",
			"infested_cobblestone",
			"infested_deepslate",
			"infested_stone",
			"netherrack",
			"end_stone",
			"obsidian",
			"crying_obsidian",
		],
	},
	masonry_blocks: {
		bricks: [
			"bricks",
			"cracked_stone_bricks",
			"cracked_deepslate_bricks",
			"cracked_nether_bricks",
			"cracked_polished_blackstone_bricks",
			"cracked_stone_bricks",
			"deepslate_bricks",
			"deepslate_tiles",
			"cracked_deepslate_tiles",
			"end_stone_bricks",
			"infested_cracked_stone_bricks",
			"infested_mossy_stone_bricks",
			"infested_stone_bricks",
			"mossy_stone_bricks",
			"mud_bricks",
			"nether_bricks",
			"polished_blackstone_bricks",
			"prismarine_bricks",
			"quartz_bricks",
			"red_nether_bricks",
			"resin_bricks",
			"stone_bricks",
			"tuff_bricks",
			"purpur_block",
			"purpur_pillar",
		],
		polished: [
			"cut_sandstone",
			"smooth_sandstone",
			"cut_red_sandstone",
			"smooth_red_sandstone",
			"polished_andesite",
			"polished_basalt",
			"polished_deepslate",
			"polished_diorite",
			"polished_granite",
			"polished_blackstone",
			"polished_tuff",
			"smooth_quartz",
			"smooth_stone",
			"smooth_basalt",
			"quartz_block",
		],
		chiseled: [
			"chiseled_deepslate",
			"chiseled_polished_blackstone",
			"chiseled_tuff",
			"chiseled_tuff_bricks",
			"chiseled_resin_bricks",
			"chiseled_sandstone",
			"chiseled_stone_bricks",
			"infested_chiseled_stone_bricks",
			"chiseled_quartz_block",
			"chiseled_red_sandstone",
			"chiseled_nether_bricks",
			"quartz_pillar",
		],
	},
	grasses: [
		"grass_block",
		"mycelium",
		"podzol",
		"crimson_nylium",
		"warped_nylium",
	],
	soil: [
		"clay",
		"coarse_dirt",
		"dirt",
		"gravel",
		"mud",
		"packed_mud",
		"red_sand",
		"rooted_dirt",
		"sand",
		"soul_sand",
		"soul_soil",
		"farmland",
		"suspicious_gravel",
		"suspicious_sand",
	],
	ores: {
		nether: ["ancient_debris", "nether_gold_ore", "nether_quartz_ore"],
		stone: [
			"coal_ore",
			"diamond_ore",
			"emerald_ore",
			"gold_ore",
			"iron_ore",
			"lapis_ore",
			"redstone_ore",
			"copper_ore",
		],
		deepslate: [
			"deepslate_coal_ore",
			"deepslate_diamond_ore",
			"deepslate_emerald_ore",
			"deepslate_gold_ore",
			"deepslate_iron_ore",
			"deepslate_lapis_ore",
			"deepslate_redstone_ore",
			"deepslate_copper_ore",
		],
	},
	precious_blocks: [
		"amethyst_block",
		"budding_amethyst",
		"coal_block",
		"diamond_block",
		"emerald_block",
		"gold_block",
		"raw_gold_block",
		"iron_block",
		"raw_iron_block",
		"lapis_block",
		"netherite_block",
		"redstone_block",
		"resin_block",
		"raw_copper_block",
	],
	copper_blocks: {
		base: {
			unwaxed: [
				"copper_block",
				"chiseled_copper",
				"cut_copper",
				"copper_bulb",
				"copper_grate",
			],
			waxed: [
				"waxed_copper_block",
				"waxed_chiseled_copper",
				"waxed_cut_copper",
				"waxed_copper_bulb",
				"waxed_copper_grate",
			],
		},
		exposed: {
			unwaxed: [
				"exposed_copper",
				"exposed_chiseled_copper",
				"exposed_cut_copper",
				"exposed_copper_bulb",
				"exposed_copper_grate",
			],
			waxed: [
				"waxed_exposed_copper",
				"waxed_exposed_chiseled_copper",
				"waxed_exposed_cut_copper",
				"waxed_exposed_copper_bulb",
				"waxed_exposed_copper_grate",
			],
		},
		weathered: {
			unwaxed: [
				"weathered_copper",
				"weathered_chiseled_copper",
				"weathered_cut_copper",
				"weathered_copper_bulb",
				"weathered_copper_grate",
			],
			waxed: [
				"waxed_weathered_copper",
				"waxed_weathered_chiseled_copper",
				"waxed_weathered_cut_copper",
				"waxed_weathered_copper_bulb",
				"waxed_weathered_copper_grate",
			],
		},
		oxidized: {
			unwaxed: [
				"oxidized_copper",
				"oxidized_chiseled_copper",
				"oxidized_cut_copper",
				"oxidized_copper_bulb",
				"oxidized_copper_grate",
			],
			waxed: [
				"waxed_oxidized_copper",
				"waxed_oxidized_chiseled_copper",
				"waxed_oxidized_cut_copper",
				"waxed_oxidized_copper_bulb",
				"waxed_oxidized_copper_grate",
			],
		},
	},
	nether_blocks: [
		"bone_block",
		"gilded_blackstone",
		"magma_block",
		"nether_wart_block",
		"shroomlight",
		"warped_wart_block",
	],
	terracotta: [
		"terracotta",
		"black_terracotta",
		"blue_terracotta",
		"brown_terracotta",
		"cyan_terracotta",
		"gray_terracotta",
		"green_terracotta",
		"light_blue_terracotta",
		"light_gray_terracotta",
		"lime_terracotta",
		"magenta_terracotta",
		"orange_terracotta",
		"pink_terracotta",
		"purple_terracotta",
		"red_terracotta",
		"white_terracotta",
		"yellow_terracotta",
	],
	glazed_terracotta: [
		"black_glazed_terracotta",
		"blue_glazed_terracotta",
		"brown_glazed_terracotta",
		"cyan_glazed_terracotta",
		"gray_glazed_terracotta",
		"green_glazed_terracotta",
		"light_blue_glazed_terracotta",
		"light_gray_glazed_terracotta",
		"lime_glazed_terracotta",
		"magenta_glazed_terracotta",
		"orange_glazed_terracotta",
		"pink_glazed_terracotta",
		"purple_glazed_terracotta",
		"red_glazed_terracotta",
		"white_glazed_terracotta",
		"yellow_glazed_terracotta",
	],
	"concrete_&_concrete_powder": {
		hardened: [
			"black_concrete",
			"blue_concrete",
			"brown_concrete",
			"cyan_concrete",
			"gray_concrete",
			"green_concrete",
			"light_blue_concrete",
			"light_gray_concrete",
			"lime_concrete",
			"magenta_concrete",
			"orange_concrete",
			"pink_concrete",
			"purple_concrete",
			"red_concrete",
			"white_concrete",
			"yellow_concrete",
		],
		powder: [
			"black_concrete_powder",
			"blue_concrete_powder",
			"brown_concrete_powder",
			"cyan_concrete_powder",
			"gray_concrete_powder",
			"green_concrete_powder",
			"light_blue_concrete_powder",
			"light_gray_concrete_powder",
			"lime_concrete_powder",
			"magenta_concrete_powder",
			"orange_concrete_powder",
			"pink_concrete_powder",
			"purple_concrete_powder",
			"red_concrete_powder",
			"white_concrete_powder",
			"yellow_concrete_powder",
		],
	},
	wool: [
		"black_wool",
		"blue_wool",
		"brown_wool",
		"cyan_wool",
		"gray_wool",
		"green_wool",
		"light_blue_wool",
		"light_gray_wool",
		"lime_wool",
		"magenta_wool",
		"orange_wool",
		"pink_wool",
		"purple_wool",
		"red_wool",
		"white_wool",
		"yellow_wool",
	],
	glass: [
		"glass",
		"tinted_glass",
		"black_stained_glass",
		"blue_stained_glass",
		"brown_stained_glass",
		"cyan_stained_glass",
		"gray_stained_glass",
		"green_stained_glass",
		"light_blue_stained_glass",
		"light_gray_stained_glass",
		"lime_stained_glass",
		"magenta_stained_glass",
		"orange_stained_glass",
		"pink_stained_glass",
		"purple_stained_glass",
		"red_stained_glass",
		"white_stained_glass",
		"yellow_stained_glass",
	],
	vegetation_blocks: [
		"brown_mushroom_block",
		"red_mushroom_block",
		"mushroom_stem",
		"cactus",
		"dried_kelp_block",
		"hay_block",
		"mangrove_roots",
		"muddy_mangrove_roots",
		"melon",
		"moss_block",
		"pale_moss_block",
		"pumpkin",
		"carved_pumpkin",
		"jack_o_lantern",
		"sculk",
		"sculk_catalyst",
		"sculk_shrieker",
		"sculk_sensor",
		"calibrated_sculk_sensor",
		"sponge",
		"wet_sponge",
		"vine",
		"glow_lichen",
	],
	cold_block: [
		"blue_ice",
		"frosted_ice",
		"ice",
		"packed_ice",
		"snow_block",
		"snow",
		"powder_snow",
	],
	coral_blocks: [
		"brain_coral_block",
		"bubble_coral_block",
		"dead_brain_coral_block",
		"dead_bubble_coral_block",
		"dead_fire_coral_block",
		"dead_horn_coral_block",
		"dead_tube_coral_block",
		"fire_coral_block",
		"horn_coral_block",
		"tube_coral_block",
	],
	utility_blocks: [
		"barrel",
		"beacon",
		"bee_nest",
		"beehive",
		"blast_furnace",
		"bookshelf",
		"chiseled_bookshelf",
		"brewing_stand",
		"cartography_table",
		"cauldron",
		"chest",
		"composter",
		"conduit",
		"crafting_table",
		"crafter",
		"daylight_detector",
		"decorated_pot",
		"dispenser",
		"dropper",
		"enchanting_table",
		"ender_chest",
		"fletching_table",
		"furnace",
		"grindstone",
		"heavy_core",
		"hopper",
		"jukebox",
		"lectern",
		"lodestone",
		"loom",
		"note_block",
		"observer",
		"piston",
		"sticky_piston",
		"redstone_lamp",
		"respawn_anchor",
		"slime_block",
		"smithing_table",
		"smoker",
		"spawner",
		"stonecutter",
		"target",
		"tnt",
		"trapped_chest",
		"trial_spawner",
		"vault",
	],
	shulker_boxes: [
		"shulker_box",
		"black_shulker_box",
		"blue_shulker_box",
		"brown_shulker_box",
		"cyan_shulker_box",
		"gray_shulker_box",
		"green_shulker_box",
		"light_blue_shulker_box",
		"light_gray_shulker_box",
		"lime_shulker_box",
		"magenta_shulker_box",
		"orange_shulker_box",
		"pink_shulker_box",
		"purple_shulker_box",
		"red_shulker_box",
		"white_shulker_box",
		"yellow_shulker_box",
	],
	prismarine: ["dark_prismarine", "prismarine", "sea_lantern"],
	misc_blocks: [
		"bedrock",
		"cobweb",
		"honey_block",
		"honeycomb_block",
		"ochre_froglight",
		"pearlescent_froglight",
		"verdant_froglight",
		"command_block",
		"chain_command_block",
		"repeating_command_block",
		"jigsaw",
		"structure_block",
		"test_block",
		"test_instance_block",
	],
};

console.log(
	"Flattened Minecraft Blocks:",
	flattenMinecraftBlocksArgs(minecraftBlocks.woods.log, minecraftBlocks.ores.stone, minecraftBlocks.woods.planks),
);